### ISSUE TITLE
Create and Implement automated testing/linting

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/C11-Kappa-Group-Project#11]
### Tasks

- [ ] Create testing & linting workflow YAML
- [ ] Add it to the repository
- [ ] Test that it works
- [ ] Ensure PRs cannot be completed without passing tests
- [ ] Fail the action if pylint score is below 8

### User Story

As a data engineer, I need to have automated tests and linting for my code, so the quality of work remains high.
