### ISSUE TITLE
Create and Add the ERD to the repository

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/C11-Kappa-Group-Project#19]
An ERD for the database holding recent plant data needs to be created and stored in the repository.

### Tasks:

- [x] Plan out ERD
- [x] Create ERD 
- [x] Review it internally, and with senior engineers
- [x] Upload it to repository

### User Story
As an engineer, I need to create a good ERD visualising the relationships and attributes, so constructing the database is easier and done correctly.
