### ISSUE TITLE
Create an extract file 

### ISSUE THREAD

**Issue by Zhi-704** [Zhi-704/C11-Kappa-Group-Project#22]
Add an extract.py file that extracts information from the Heroku API into the pipeline folder.

### Tasks

- [ ] Extract relevant information from the API 
- [ ] Test that it works
- [ ] Ensure pylint is over 8

### User Story

As a developer, I need to extract relevant information from an API, so that I can exclude any unnecessary info and use the rest for analysis.
