### ISSUE TITLE
Create load script

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/C11-Kappa-Group-Project#23]
A load script needs to be created to load the clean data into the Microsoft SQL Server Database

### Tasks

- [x] Create load script
- [ ] Write tests
- [ ] Review it with team
- [ ] Add to the repository

### User story

As an engineer, I need to be able to be able to automate data insertion, so new plant readings can be continuously inserted.

**Comment by e-lemma** [comment]
Got the load.py functioning, and consequently the whole ETL process too. Just need to refactor and finish writing the tests
