### ISSUE TITLE
Create a schema.sql 

### ISSUE THREAD

**Issue by Zhi-704** [Zhi-704/C11-Kappa-Group-Project#30]
Add a schema.sql file that creates the tables in the main repository

### Tasks

- [x] Create an sql file that creates tables, reflecting the ERD diagram
- [ ] Seed the data and check if it works
- [ ] Add to repository after approval

### User Story

As a developer, I need to have an sql file that recreates all the tables I need for my data, so that the database is easy to reset and test.
