### ISSUE TITLE
Create a dashboard wireframe

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/C11-Kappa-Group-Project#31]
### Tasks

- [ ] Review data, client needs
- [ ] Decide on visualisations to implement
- [ ] Create dashboard wireframe
- [ ] Review it with team, and senior engineers
- [ ] Upload to repository

### User story

As an engineer, I need to plan out the dashboard, so that the final dashboard meets the needs of the client and has all the necessary functionality and visualisations.
